### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by scen** [dchen496/bigDSM#1]
why

**Comment by dchen496** [comment]
sad boys

**Comment by akshayravikumar** [comment]
same

On Wed, May 4, 2016 at 5:21 PM, Douglas Chen <notifications@github.com>
wrote:

> Closed #1 <https://github.com/dchen496/bigDSM/issues/1>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dchen496/bigDSM/issues/1#event-650807098>
>



-- 
Akshay Ravikumar
Massachusetts Institute of Technology, Class of 2018
Department of Electrical Engineering and Computer Science
akshayr@mit.edu | (925) 413 6077 | akshayr.me
